# Generated by Django 3.2.21 on 2023-09-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0002_alter_post_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
